In [1]:
# Theoretical Questions:-

In [2]:
# Question_1st:- Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?


In [3]:
# NumPy is a Python library that provides powerful tools for numerical computing. 
  #  It enhances Python's capabilities by offering:

      # 1.Efficient Arrays: NumPy introduces the ndarray object, which allows for efficient storage and manipulation of large datasets, much faster than Python's built-in lists.

      # 2.Mathematical Functions: It includes a wide range of mathematical functions to perform complex calculations on arrays, like matrix operations, Fourier transforms, and statistical analyses.

      # 3.Vectorization: NumPy enables vectorized operations, meaning you can apply functions to entire arrays without writing loops, making the code faster and easier to read.

      # 4.Interoperability: It integrates well with other scientific computing libraries like SciPy and Pandas, making it a key tool in data analysis workflows.

# NumPy makes numerical operations in Python more efficient, faster, and easier, which is essential for scientific computing and data analysis.

In [4]:
# Question_2nd:- Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

In [7]:
# np.mean() and np.average() in NumPy calculate the average of an array, but they have some differences:
  
# np.mean():-
           # Purpose: Computes the simple arithmetic mean (average) of the elements in an array.
           # Usage: Use when you want a straightforward average of values.
# example of np.mean():-
import numpy as np
data = np.array([1, 2, 3, 4, 5])
result = np.mean(data)
print(result)


# np.average():-
           # Purpose: Computes the weighted average, where each element can have a different weight.
           # Usage: Use when you need to account for different weights for elements
# example of np.average():-
weights = np.array([1, 2, 3, 4, 5])
result = np.average(data, weights=weights)  # Output: 3.6667
print(result)



3.0
3.6666666666666665


In [8]:
# Question_3rd:- Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

In [16]:
# you can reverse an array along different axes using slicing or specific functions. 

# 1. Reversing a 1D Array:- Method: Use slicing with [::-1] to reverse the array.

# Example of 1D Array reverse:-
import numpy as np
arr_1d = np.array([1, 2, 3, 4, 5])
reversed_arr_1d = arr_1d[::-1]
print(reversed_arr_1d)
print("===================")

# 2. Reversing a 2D Array:- You can reverse along different axes:

   # a.Reversing along rows (axis 0):-Method: Use slicing [::-1, :].
# Example of  Reversing along rows (axis 0):-

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_rows = arr_2d[::-1, :]
print(reversed_rows)
print("================")

  # b.Reversing along columns (axis 1):-Method: Use slicing [:, ::-1].
# Example of Reversing along columns (axis 1):-
reversed_columns = arr_2d[:, ::-1]
print(reversed_columns)
print("===============")
 
    # C.Reversing both axes:-Method: Use slicing [::-1, ::-1].
# Example of Reversing both axes:-
reversed_both = arr_2d[::-1, ::-1]
print(reversed_both)


[5 4 3 2 1]
[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [17]:
# Question_4th:- How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.


In [18]:
# the data type of elements in a NumPy array, you can use the .dtype attribute. Here's how you do it:

# 1.Memory Management:
           # Efficient Storage: Different data types use different amounts of memory. For example, an int32 takes 4 bytes, while an int64 takes 8 bytes. Choosing the right data type can save memory, especially with large arrays.
           # Example: Using int8 (1 byte) instead of int64 (8 bytes) for storing small integers reduces memory usage by 8 times.
# 2.Performance:
          # Faster Operations: Operations on smaller data types (e.g., int32 vs. int64) are generally faster because they require less data to be processed.
          # Example: If you’re performing calculations on a large dataset of small integers, using int32 instead of int64 can speed up the computations.
# Data Type Check: Use .dtype to determine the data type.
#Importance: Proper data type selection optimizes memory usage and improves computational speed, which is crucial in handling large datasets.


# example:-
import numpy as np
arr = np.array([1, 2, 3])
print(arr.dtype)  # Output: int32 (or int64 depending on your system)

int64


In [20]:
# Question_5th:- Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

In [21]:
# It is a powerful, multidimensional container for homogeneous data, meaning all elements have the same data type.

# Key Features of ndarrays:
  # 1.Multidimensionality: ndarrays can have multiple dimensions, such as 1D (vectors), 2D (matrices), or higher dimensions.
  # 2.Homogeneous Data: All elements in an ndarray must be of the same data type (e.g., all integers, all floats).
  # 3.Efficient Memory Use: ndarrays are stored in contiguous memory locations, which allows for fast access and efficient storage compared to standard Python lists.
  # 4.Broadcasting: NumPy supports broadcasting, which allows operations on arrays of different shapes without needing explicit looping.
  # 5.Vectorized Operations: Operations on ndarrays are applied element-wise without the need for explicit loops, leading to faster and more concise code.

    
# Differences from Standard Python Lists:
# 1.Data Type Consistency:
                   # ndarray: All elements must have the same data type.
                   # Python List: Elements can have mixed data types.
# 2.Performance:

                   # ndarray: Faster for numerical computations due to contiguous memory storage and support for vectorized operations.
                   # Python List: Slower for large-scale numerical operations because it lacks these optimizations.
# 3.Memory Efficiency:

                   # ndarray: More memory-efficient due to fixed-size elements and contiguous memory layout.
                   # Python List: Less memory-efficient, with each element being a full-fledged Python object, leading to overhead.
# 4.Multidimensional Support:

                   # ndarray: Naturally supports multiple dimensions, such as 2D, 3D, etc.
                   # Python List: Can mimic multidimensionality with nested lists, but it is less efficient and harder to work with.

In [22]:
# Question_6th:- Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.


In [23]:
# NumPy arrays offer significant performance benefits over Python lists for large-scale numerical operations due to:

# 1.Faster Computations:
             # NumPy arrays are optimized for numerical operations with C-based implementation, making them much faster than Python lists, especially for large datasets.
# 2.Memory Efficiency:
             # NumPy arrays use contiguous memory and fixed-size elements, reducing memory usage compared to Python lists, which have overhead due to each element being a full Python object.
# 3.Vectorized Operations:

              # NumPy supports vectorized operations, allowing you to perform element-wise calculations without explicit loops, which speeds up processing.
# NumPy arrays are faster, more memory-efficient, and support vectorized operations, making them ideal for large-scale numerical tasks compared to Python lists.



In [24]:
# Question_7:- Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage andoutput.


In [30]:
# vstack() and hstack() are used to stack arrays along different axes:

# 1. vstack() (Vertical Stack):- Purpose: Stacks arrays vertically (row-wise), one on top of the other.

# Example of vstack:-

import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.vstack((arr1, arr2))
print(result)
print("=================")

# 2.hstack() (Horizontal Stack):-Purpose: Stacks arrays horizontally (column-wise), side by side.

# Example of hstack:-
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.hstack((arr1, arr2))
print(result)


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [31]:
# Question_8th:-. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

In [34]:
# fliplr() and flipud() are used to reverse the order of elements in arrays along different dimensions:

# fliplr() (Flip Left-Right):-
                    # Purpose: Reverses the order of elements along the horizontal axis (left to right).
                    # Effect: Applies to 2D arrays, flipping columns from left to right.
# Example:-
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
result = np.fliplr(arr)
print(result)
print("=========================================")


# flipud() (Flip Up-Down):-
                  # Purpose: Reverses the order of elements along the vertical axis (top to bottom).
                  # Effect: Applies to 2D arrays, flipping rows from top to bottom
        
# Example:-
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
result = np.flipud(arr)
print(result)


[[3 2 1]
 [6 5 4]]
[[4 5 6]
 [1 2 3]]


In [1]:
# Question_9th:- Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

In [3]:
# the array_split() method in NumPy is used to split an array into multiple sub-arrays. It provides flexibility in how the array is divided, including handling cases where the array cannot be evenly split.


# Functionality:
           # Purpose: To split an array into a specified number of sub-arrays or based on specific indices.
           # Usage: np.array_split(array, indices_or_sections)
# Handling Uneven Splits:
                # Even Splits: If the total number of elements can be evenly divided by the number of sections, each sub-array will have the same size.
                # Uneven Splits: When the total number of elements does not divide evenly, the resulting sub-arrays will have sizes as equal as possible. Some sub-arrays may have one more element than others.

        
# Splitting into Equal Sections:-

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
result = np.array_split(arr, 4)
print(result)


# Splitting by Indices::-
indices = [2, 5, 7]
result = np.array_split(arr, indices)
print(result)


[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]
[array([1, 2]), array([3, 4, 5]), array([6, 7]), array([8, 9])]


In [10]:
# Question_10:-Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

In [13]:
# Vectorization:
      # Concept: Vectorization refers to applying operations on entire arrays at once, rather than using explicit loops. This leverages low-level optimizations for faster computation.
# Example: Instead of looping through each element to add 5, you can do:
import numpy as np
arr = np.array([1, 2, 3])
result = arr + 5  

print(result)
print("=========================")

# Broadcasting:
           # Concept: Broadcasting allows NumPy to perform operations on arrays of different shapes by automatically expanding the smaller array to match the larger one’s shape.

# Example:
arr = np.array([[1, 2], [3, 4]])
result = arr + 10
print(result)
print("========================================================")

import numpy as np


arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_1d = np.array([10, 20, 30])
print(arr_2d)
print("============================")
print(arr_1d)
print("===========================")
result = arr_2d * arr_1d
print(result)






[6 7 8]
[[11 12]
 [13 14]]
[[1 2 3]
 [4 5 6]]
[10 20 30]
[[ 10  40  90]
 [ 40 100 180]]


In [14]:
# Practical Questions:-

In [15]:
# Question_1st:- Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [18]:
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
arr = np.random.randint(1, 101, size=(3, 3))
print("Original Array:")
print(arr)
print("================================")
print("\nTransposed Array:")

print(arr.T)

Original Array:
[[70 85  5]
 [ 2 87 31]
 [71 44 85]]

Transposed Array:
[[70  2 71]
 [85 87 44]
 [ 5 31 85]]


In [19]:
# Question_2nd:- Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [23]:
import numpy as np
arr_1d = np.arange(10)
print("Original 1D Array:")
print(arr_1d)
print("=======================")
# Reshape the 1D array into a 2x5 array
arr_2x5 = arr_1d.reshape(2, 5)
print("\nReshaped into 2x5 Array:")
print(arr_2x5)
print("===================")

# Reshape the 2x5 array into a 5x2 array
arr_5x2 = arr_2x5.reshape(5, 2)
print("\nReshaped into 5x2 Array:")
print(arr_5x2)


Original 1D Array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped into 2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped into 5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [24]:
# Question_3rd:- Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [27]:
import numpy as np

# Create a 4x4 array with random float values
arr_4x4 = np.random.rand(4, 4)
print("Original 4x4 Array:")
print(arr_4x4)

print("===========================")
# Add a border of zeros around the 4x4 array
arr_6x6 = np.pad(arr_4x4, pad_width=1, mode='constant', constant_values=0)
print("\n6x6 Array with Zero Border:")
print(arr_6x6)


Original 4x4 Array:
[[0.05800716 0.29064603 0.58216316 0.60941128]
 [0.37868156 0.65306847 0.54691625 0.38697215]
 [0.66436172 0.52065112 0.54066659 0.3682084 ]
 [0.77402872 0.7284984  0.55421911 0.52680138]]

6x6 Array with Zero Border:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.05800716 0.29064603 0.58216316 0.60941128 0.        ]
 [0.         0.37868156 0.65306847 0.54691625 0.38697215 0.        ]
 [0.         0.66436172 0.52065112 0.54066659 0.3682084  0.        ]
 [0.         0.77402872 0.7284984  0.55421911 0.52680138 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [28]:
# Question_4th:- Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [29]:
import numpy as np
arr = np.arange(10, 65, 5)
print(arr)


[10 15 20 25 30 35 40 45 50 55 60]


In [30]:
# Question_5th:- Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations(uppercase, lowercase, title case, etc.) to each element.

In [32]:
import numpy as np

arr = np.array(['python', 'numpy', 'pandas'])

uppercase = np.char.upper(arr)
lowercase = np.char.lower(arr)
titlecase = np.char.title(arr)

print("Original Array:")
print(arr)
print("\nUppercase:")
print(uppercase)
print("\nLowercase:")
print(lowercase)
print("\nTitle Case:")
print(titlecase)


Original Array:
['python' 'numpy' 'pandas']

Uppercase:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase:
['python' 'numpy' 'pandas']

Title Case:
['Python' 'Numpy' 'Pandas']


In [33]:
# Question_6th:-. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [34]:
import numpy as np

# Create a NumPy array of words
words = np.array(['hello', 'world', 'numpy'])

# Insert a space between each character of every word
words_with_spaces = np.char.join(' ', words)

# Print the result
print("Original Array:")
print(words)
print("\nWords with Spaces:")
print(words_with_spaces)


Original Array:
['hello' 'world' 'numpy']

Words with Spaces:
['h e l l o' 'w o r l d' 'n u m p y']


In [35]:
# Question:-7th:- Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [38]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Element-wise addition
addition = array1 + array2

# Element-wise subtraction
subtraction = array1 - array2

# Element-wise multiplication
multiplication = array1 * array2

# Element-wise division
division = array1 / array2

# Print the results
print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nElement-wise Addition:")
print(addition)
print("\nElement-wise Subtraction:")
print(subtraction)
print("\nElement-wise Multiplication:")
print(multiplication)
print("\nElement-wise Division:")
print(division)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Element-wise Addition:
[[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Element-wise Multiplication:
[[ 7 16 27]
 [40 55 72]]

Element-wise Division:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [39]:
# Question_8th:- Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements

In [41]:
import numpy as np
identity_matrix = np.eye(5)
diagonal_elements = np.diag(identity_matrix)

print("Identity Matrix:")
print(identity_matrix)

print("Diagonal Elements:")
print(diagonal_elements)


Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements:
[1. 1. 1. 1. 1.]


In [42]:
# Question:-9th:- Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers inthis array

In [43]:
import numpy as np

# Simplified function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    # Check for factors from 5 to sqrt(n)
    for i in range(5, int(n**0.5) + 1, 6):
        if n % i == 0 or n % (i + 2) == 0:
            return False
    return True

# Generate a NumPy array of 100 random integers between 0 and 1000
random_array = np.random.randint(0, 1001, size=100)

# Find and sort all prime numbers in the array
prime_numbers = np.array(sorted([num for num in random_array if is_prime(num)]))

print("Random Array:")
print(random_array)

print("Sorted Prime Numbers:")
print(prime_numbers)


Random Array:
[116 953  72 137 175 947 466 818 895 391  80 618 764 736 268 119 882 475
 853 149 262 891 125 822 606 173 155 327 579 954 901 907 989 728 764 237
 245 653  46 306 435 706 181 355 685 741 846 217 266 116  61 653 329 835
 394 107 921   4 564  71 235 198  82 198 120 167 901 588  35 945 973 758
  73 416 337 300 596 554 220 209 236 194 277 801 629 814 663 691 273  48
 703  85 687 539 357 824 369 822 853 563]
Sorted Prime Numbers:
[ 61  71  73 107 137 149 167 173 181 277 337 563 653 653 691 853 853 907
 947 953]


In [44]:
# Question:-10:- Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [48]:
import numpy as np

# Generate a NumPy array of daily temperatures for a month (30 days)
daily_temperatures = np.random.uniform(low=-10, high=35, size=28)

# Reshape the array into a 2D array where each row represents a week (4 weeks of 7 days)
weekly_temperatures = daily_temperatures.reshape(4, 7)

# Calculate the weekly averages
weekly_averages = np.mean(weekly_temperatures, axis=1)

print("Daily Temperatures:")
print(daily_temperatures)

print("\nWeekly Temperatures:")
print(weekly_temperatures)

print("\nWeekly Averages:")
print(weekly_averages)


Daily Temperatures:
[10.34722609 -1.60168076 22.1637312  34.31434126 -8.84137283 15.39227047
 28.60803283 28.08729295 22.48756976  3.84726163 18.96973683  5.14813977
 -6.63482822 10.81846618  1.14867769  5.2616379  31.29248187  8.48510873
 22.46068346 28.5344175   4.75759479  3.23789751 -7.85049103 15.1228694
 17.52647978 -9.81836871  0.67702123  3.36241677]

Weekly Temperatures:
[[10.34722609 -1.60168076 22.1637312  34.31434126 -8.84137283 15.39227047
  28.60803283]
 [28.08729295 22.48756976  3.84726163 18.96973683  5.14813977 -6.63482822
  10.81846618]
 [ 1.14867769  5.2616379  31.29248187  8.48510873 22.46068346 28.5344175
   4.75759479]
 [ 3.23789751 -7.85049103 15.1228694  17.52647978 -9.81836871  0.67702123
   3.36241677]]

Weekly Averages:
[14.34036404 11.8176627  14.56294313  3.17968928]
